name: Execute E2E tests
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      browser:
        description: 'BROWSER'
        required: true
        default: 'Chrome'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Build docker container
        run: docker build . -t e2e:v1
      - name: Run tests in docker container
        run: docker run -e BROWSER=${{ github.event.inputs.browser }} e2e:v1
